#服务器端口
server:
  port: 2026
  servlet:
    context-path: /sso

#数据源配置
spring:
  datasource:
    url: jdbc:mysql://%s:%s?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: ybbqwert
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最小
      initial-size: 10
      min-idle: 10
      max-active: 200
      #配置获取连接等待超时的时间
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      #验证连接是否有效。此参数必须设置为非空字符串，下面三项设置成true才能生效
      validation-query: SELECT 1
      #指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从  池中去除.
      test-while-idle: true
      #指明是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
      test-on-borrow: true
      #指明是否在归还到池中前进行检验
      test-on-return:  true
      #打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filter: stat,wall,log4j
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1000;druid.stat.logSlowSql=true
      #合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      remove-abandoned: true
      remove-abandoned-timeout-millis: 90
    session:
      store-type: redis
  #redis
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 500
#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:/com/sso/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.oss.**.entity
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#微信开发的appId钥匙配置
constants:
  #WECHAT
  weChatAppId: wx4ca477e77ef1391a
  weChatAppSecret: 42857600ffbffa9fad000720907b8f1c
  weChatTokenUrl: https://open.weixin.qq.com/connect/oauth2/authorize?
  # 用户同意授权,回调url----你的域名后面再加上/getcode
  weChatRedirectUrl: api/weChatcallback.do
  scope: snsapi_userinfo
  state: session
v:
  im:
    admin:
      id: cb0c145a6c104497942525f8c984f9d9
    default:
      chat:
        id: e83018ca92cb441aa93484af2deb8456

swagger:
  base-packages:
    - com.sso.panelapi.controller
    - com.sso.satapi.power
    - com.sso.auth.controller
    - com.sso.chatapi.controller

#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000
#ribbon的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000

#定义队列名称
myqueue: test-que
topicqueue: topicqueue