#服务器端口
server:
  port: 2021

#==================== logging Setting =====================#
logging:
  level:
    org.springframework: info
    com.anaysis.executSupervise: info
log4j:
  logger:
    com:
      anaysis:
        mapper=DEBUG:

spring:
  influx:
    url: http://39.98.206.228:8086
    password: admin
    user: 123
    database: add_test
  datasource:
    #url: jdbc:mysql://127.0.0.1:3306/ybb?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    url: jdbc:mysql://39.98.57.236:3378/yb_test?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: saturn
    password: hopeybb!@#
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最小
      initial-size: 20
      min-idle: 10
      max-active: 1000
      #配置获取连接等待超时的时间
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      #验证连接是否有效。此参数必须设置为非空字符串，下面三项设置成true才能生效
      validation-query: SELECT 1
      #指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除.
      test-while-idle: true
      #指明是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
      test-on-borrow: true
      #指明是否在归还到池中前进行检验
      test-on-return:  true
      #打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filter: stat,wall,log4j
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1000;druid.stat.logSlowSql=true
      #合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      remove-abandoned: true
      remove-abandoned-timeout-millis: 90
  data:
    mongodb:
      primary:
        database: ybb
        host: 39.98.206.228
        port: 27172
      nxjsj:
        database: jsj
        host: 39.98.206.228
        port: 27172
      fuli:
        database: fuli
        host: 39.98.206.228
        port: 27172
      baofeng:
        database: bf
        host: 39.98.206.228
        port: 27172
      xingyi:
        database: xingyi
        host: 39.98.206.228
        port: 27172
      hbhr:
        database: hbhr
        host: 39.98.206.228
        port: 27172
      demo:
        database: demo
        host: 39.98.206.228
        port: 27172
      nxhr:
        database: nxhr
        host: 39.98.206.228
        port: 27172

#feign配置
feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: true
  httpclient:
    enabled: false

#hystrix配置
hystrix:
  threadpool:
    default:
      coreSize: 300
      maxQueueSize: 1000
      queueSizeRejectionThreshold: 800
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

#ribbon配置
ribbon:
  #对当前实例的重试次数
  MaxAutoRetries: 1
  #切换实例的重试次数
  MaxAutoRetriesNextServer: 2
  #请求处理的超时时间
  ReadTimeout: 60000
  #请求连接的超时时间
  ConnectTimeout: 60000
  #对所有操作请求都进行重试
  OkToRetryOnAllOperations: true
swagger:
  base-packages:ExecutCheck
    - com.anaysis.command
#定义队列名称
myqueue: test-que
topicqueue: topicqueue